{
  "headers": {
    "client_id": "2324",
    "client_secret": "242535",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.29.2",
    "accept": "*/*",
    "postman-token": "f2ba4a0d-3c58-4a86-a55b-f19934bf32dc",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "126"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/customer",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/customer",
  "listenerPath": "/api/*",
  "relativePath": "/api/customer",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/customer",
  "rawRequestPath": "/api/customer",
  "remoteAddress": "/127.0.0.1:53890",
  "requestPath": "/api/customer"
}